import { beforeEach, describe, expect, it, vi } from "vitest";
import bcrypt from "bcryptjs";
import { generate } from "otplib";

vi.mock("./db", () => ({
  getLocalUserByEmail: vi.fn(), createLocalUser: vi.fn(), createAuthSession: vi.fn(), deleteAuthSession: vi.fn(), getUserBySessionToken: vi.fn(), hashSessionToken: vi.fn((token: string) => `hash:${token}`), updateTwoFactorEnrollment: vi.fn(), verifyAuthSessionTwoFactor: vi.fn(), setEmailVerificationToken: vi.fn(), consumeEmailVerificationToken: vi.fn(), setPasswordResetToken: vi.fn(), getUserByPasswordResetToken: vi.fn(), completePasswordReset: vi.fn(),
}));
vi.mock("./email", () => ({ deliverAccountEmail: vi.fn() }));
import { appRouter } from "./routers";
import { resetRateLimits } from "./security";
import * as db from "./db";
const dbMock = vi.mocked(db);
const csrfToken = "a".repeat(64);
const user = { id: 7, openId: "local_7", email: "alex@example.com", name: "Alex", passwordHash: "$2b$12$abcdefghijklmnopqrstuuQmF4p3JcV0Hf2J5eZxYJ3b4tK6", loginMethod: "local", role: "user", emailVerified: 1, twoFactorEnabled: 0, twoFactorSecret: "JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP", twoFactorEnrollmentId: "12345678901234567890123456789012" };
function context(cookie = "") { const cookies: any[] = []; const fullCookie = `${cookie}${cookie ? "; " : ""}local_csrf=${csrfToken}`; const ctx = { user: undefined, req: { protocol: "https", headers: { cookie: fullCookie } }, res: { cookie: (name: string, value: string, options: Record<string, unknown>) => cookies.push({ name, value, options }), clearCookie: vi.fn(), setHeader: vi.fn() } } as any; return { ctx, cookies }; }
const registerInput = { email: "Alex@Example.com", password: "correct horse battery staple", csrfToken };

describe("local authentication", () => {
  beforeEach(() => { vi.clearAllMocks(); resetRateLimits(); });
  it("rejects malformed registration input before touching the data layer", async () => { const { ctx } = context(); await expect(appRouter.createCaller(ctx).localAuth.register({ email: "not-an-email", password: "short", csrfToken })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(dbMock.getLocalUserByEmail).not.toHaveBeenCalled(); });
  it("handles duplicate registration without account enumeration", async () => { dbMock.getLocalUserByEmail.mockResolvedValue(user as any); const { ctx } = context(); const result = await appRouter.createCaller(ctx).localAuth.register(registerInput); expect(result.accepted).toBe(true); expect(dbMock.createLocalUser).not.toHaveBeenCalled(); });
  it("hashes a new password and sends email verification without creating a session", async () => { dbMock.getLocalUserByEmail.mockResolvedValue(undefined); dbMock.createLocalUser.mockResolvedValue(7); const { ctx, cookies } = context(); const result = await appRouter.createCaller(ctx).localAuth.register(registerInput); expect(result.accepted).toBe(true); expect(dbMock.createLocalUser).toHaveBeenCalledWith("alex@example.com", expect.stringMatching(/^\$2[aby]\$/), undefined); expect(dbMock.createAuthSession).not.toHaveBeenCalled(); expect(cookies).toHaveLength(0); });
  it("rejects incorrect passwords and rate limits repeated attempts", async () => { dbMock.getLocalUserByEmail.mockResolvedValue(user as any); const { ctx } = context(); for (let i = 0; i < 5; i++) await expect(appRouter.createCaller(ctx).localAuth.login({ email: user.email, password: "wrong", csrfToken })).rejects.toMatchObject({ code: "UNAUTHORIZED" }); await expect(appRouter.createCaller(ctx).localAuth.login({ email: user.email, password: "wrong", csrfToken })).rejects.toMatchObject({ code: "TOO_MANY_REQUESTS" }); });
  it("creates a challenge session for a valid password when 2FA is enabled", async () => { const hash = await bcrypt.hash("password", 4); dbMock.getLocalUserByEmail.mockResolvedValue({ ...user, passwordHash: hash, twoFactorEnabled: 1 } as any); const { ctx, cookies } = context(); const result = await appRouter.createCaller(ctx).localAuth.login({ email: user.email, password: "password", csrfToken }); expect(result.requiresTwoFactor).toBe(true); expect(dbMock.createAuthSession).toHaveBeenCalledWith(7, expect.stringMatching(/^hash:/), expect.any(Date), 0, expect.objectContaining({ ipAddress: undefined })); expect(cookies[0]?.name).toBe("local_session"); });
  it("protects account access when no valid session exists", async () => { dbMock.getUserBySessionToken.mockResolvedValue(undefined); const { ctx } = context("local_session=expired-token"); await expect(appRouter.createCaller(ctx).account.overview()).rejects.toMatchObject({ code: "UNAUTHORIZED" }); });
  it("persists successful 2FA verification and recovery-code hashes", async () => { dbMock.getUserBySessionToken.mockResolvedValue(user as any); const { ctx } = context("local_session=active-token"); const code = await generate({ secret: user.twoFactorSecret }); const result = await appRouter.createCaller(ctx).twoFactor.verifyEnrollment({ enrollmentId: user.twoFactorEnrollmentId, code, csrfToken }); expect(result.accepted).toBe(true); expect(result.recoveryCodes).toHaveLength(8); const update = dbMock.updateTwoFactorEnrollment.mock.calls[0]?.[1] as any; expect(update).toMatchObject({ twoFactorEnabled: 1, twoFactorEnrollmentId: null }); expect(JSON.parse(update.recoveryCodesHash)).toHaveLength(8); expect(JSON.parse(update.recoveryCodesHash)[0]).toMatch(/^\$2[aby]\$/); });
  it("validates CSRF tokens on state-changing actions", async () => { const { ctx } = context("local_session=active-token"); await expect(appRouter.createCaller(ctx).localAuth.logout({ csrfToken: "b".repeat(64) })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("deletes the active session and expires the cookie on logout", async () => { const { ctx, cookies } = context("local_session=active-token"); const result = await appRouter.createCaller(ctx).localAuth.logout({ csrfToken }); expect(result).toEqual({ success: true }); expect(dbMock.deleteAuthSession).toHaveBeenCalledWith("active-token"); expect(cookies[0]?.options).toMatchObject({ maxAge: 0, httpOnly: true, secure: true }); });
});
