import bcrypt from "bcryptjs";
import { randomBytes } from "node:crypto";
import { parse } from "cookie";
import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { generateSecret, generateURI, verify } from "otplib";
import { getLocalUserByEmail, createLocalUser, createAuthSession, deleteAuthSession, getUserBySessionToken, getActiveSessions, revokeAuthSession, revokeOtherAuthSessions, addSecurityEvent, getSecurityEvents, hashSessionToken, updateTwoFactorEnrollment, verifyAuthSessionTwoFactor, setEmailVerificationToken, consumeEmailVerificationToken, setPasswordResetToken, getUserByPasswordResetToken, completePasswordReset } from "./db";
import { deliverAccountEmail } from "./email";
import { checkLoginRateLimit, clientKey, issueCsrfToken, recordLoginAttempt, safeEqual } from "./security";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { socialProviders } from "./socialOAuth";
import { publicProcedure, router } from "./_core/trpc";

export const LOCAL_SESSION_COOKIE = "local_session";
export const CSRF_COOKIE = "local_csrf";
const SESSION_TTL_MS = 1000 * 60 * 60 * 24 * 7;
const TOKEN_TTL_MS = 1000 * 60 * 30;
const emailSchema = z.string().trim().toLowerCase().email("Enter a valid email address").max(320);
const passwordSchema = z.string().min(12, "Use at least 12 characters").max(128);
const csrfSchema = z.string().length(64);
const withCsrf = <T extends z.ZodRawShape>(shape: T) => z.object({ ...shape, csrfToken: csrfSchema });

function cookieOptions(req: any) { return { httpOnly: true, secure: req.protocol === "https", sameSite: "lax" as const, path: "/", maxAge: SESSION_TTL_MS }; }
function readCookie(req: any, name: string) { return parse(req.headers.cookie || "")[name]; }
function safeUser(user: any) { return user && { id: user.id, email: user.email, name: user.name, role: user.role, emailVerified: Boolean(user.emailVerified), twoFactorEnabled: Boolean(user.twoFactorEnabled), sessionTwoFactorVerified: Boolean(user.sessionTwoFactorVerified) }; }
function requireCsrf(ctx: any, token: string) { if (!safeEqual(readCookie(ctx.req, CSRF_COOKIE), token)) throw new TRPCError({ code: "FORBIDDEN", message: "Your security token is invalid or expired. Refresh and try again." }); }
async function establishSession(ctx: any, userId: number, twoFactorVerified = 1) { const raw = randomBytes(32).toString("hex"); const forwarded = String(ctx.req.headers["x-forwarded-for"] || "").split(",")[0].trim(); const ipAddress = forwarded || ctx.req.socket?.remoteAddress || undefined; await createAuthSession(userId, hashSessionToken(raw), new Date(Date.now() + SESSION_TTL_MS), twoFactorVerified, { ipAddress, userAgent: ctx.req.headers["user-agent"] }); ctx.res.cookie(LOCAL_SESSION_COOKIE, raw, cookieOptions(ctx.req)); }
async function currentLocalUser(ctx: any) { const token = readCookie(ctx.req, LOCAL_SESSION_COOKIE); return token ? getUserBySessionToken(token) : undefined; }
function genericRegistrationMessage() { return "If this address is eligible, we’ll continue with account setup."; }
function requestMetadata(ctx: any) { const forwarded = String(ctx.req.headers["x-forwarded-for"] || "").split(",")[0].trim(); return { ipAddress: forwarded || ctx.req.socket?.remoteAddress, userAgent: ctx.req.headers["user-agent"] }; }

export const appRouter = router({
  system: systemRouter,
  socialAuth: router({ providers: publicProcedure.query(() => socialProviders()) }),
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const options = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...options, maxAge: -1 }); return { success: true } as const; }) }),
  localAuth: router({
    csrfToken: publicProcedure.query(({ ctx }) => { const token = readCookie(ctx.req, CSRF_COOKIE) || issueCsrfToken(); ctx.res.cookie(CSRF_COOKIE, token, { ...cookieOptions(ctx.req), maxAge: 1000 * 60 * 60 * 2 }); return { token }; }),
    me: publicProcedure.query(async ({ ctx }) => { const user = await currentLocalUser(ctx); return user && (!user.twoFactorEnabled || user.sessionTwoFactorVerified) ? safeUser(user) : undefined; }),
    register: publicProcedure.input(withCsrf({ email: emailSchema, password: passwordSchema, name: z.string().trim().min(1).max(80).optional() })).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const existing = await getLocalUserByEmail(input.email); if (existing) return { accepted: true, message: genericRegistrationMessage() }; const passwordHash = await bcrypt.hash(input.password, 12); try { const id = await createLocalUser(input.email, passwordHash, input.name); const token = randomBytes(32).toString("hex"); await setEmailVerificationToken(id, hashSessionToken(token), new Date(Date.now() + TOKEN_TTL_MS)); await deliverAccountEmail({ to: input.email, kind: "verify-email", token, expiresAt: new Date(Date.now() + TOKEN_TTL_MS) }); } catch { /* Keep registration response non-enumerating. */ } return { accepted: true, message: genericRegistrationMessage() }; }),
    login: publicProcedure.input(withCsrf({ email: emailSchema, password: z.string().min(1).max(128) })).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const key = clientKey(ctx.req, input.email); const limit = checkLoginRateLimit(key); if (!limit.allowed) throw new TRPCError({ code: "TOO_MANY_REQUESTS", message: `Too many attempts. Try again in ${limit.retryAfterSeconds} seconds.` }); const user = await getLocalUserByEmail(input.email); const valid = user?.passwordHash ? await bcrypt.compare(input.password, user.passwordHash) : false; recordLoginAttempt(key, Boolean(valid)); if (!user || !valid) throw new TRPCError({ code: "UNAUTHORIZED", message: "Email or password is incorrect." }); await establishSession(ctx, user.id, user.twoFactorEnabled ? 0 : 1); void addSecurityEvent(user.id, user.twoFactorEnabled ? "login.password_2fa_required" : "login.success", requestMetadata(ctx)); return { user: safeUser({ ...user, sessionTwoFactorVerified: user.twoFactorEnabled ? 0 : 1 }), requiresTwoFactor: Boolean(user.twoFactorEnabled) }; }),
    logout: publicProcedure.input(withCsrf({})).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const token = readCookie(ctx.req, LOCAL_SESSION_COOKIE); const user = await currentLocalUser(ctx); if (token) await deleteAuthSession(token); if (user) void addSecurityEvent(user.id, "session.logout", requestMetadata(ctx)); ctx.res.cookie(LOCAL_SESSION_COOKIE, "", { ...cookieOptions(ctx.req), maxAge: 0 }); return { success: true } as const; }),
  }),
  account: router({ overview: publicProcedure.query(async ({ ctx }) => { const user = await currentLocalUser(ctx); if (!user || (user.twoFactorEnabled && !user.sessionTwoFactorVerified)) throw new TRPCError({ code: "UNAUTHORIZED", message: "Complete two-factor verification." }); return { user: safeUser(user), security: { twoFactorReady: true, recoveryGuidance: "Store recovery codes offline and never share them." } }; }), events: publicProcedure.input(z.object({ csrfToken: csrfSchema })).query(async ({ ctx, input }) => { requireCsrf(ctx, input.csrfToken); const user = await currentLocalUser(ctx); if (!user) throw new TRPCError({ code: "UNAUTHORIZED", message: "Please sign in." }); return getSecurityEvents(user.id); }), sessions: publicProcedure.input(z.object({ csrfToken: csrfSchema })).query(async ({ ctx, input }) => { requireCsrf(ctx, input.csrfToken); const user = await currentLocalUser(ctx); const currentToken = readCookie(ctx.req, LOCAL_SESSION_COOKIE); if (!user || !currentToken) throw new TRPCError({ code: "UNAUTHORIZED", message: "Please sign in." }); const currentHash = hashSessionToken(currentToken); const sessions = await getActiveSessions(user.id); return sessions.map(session => ({ id: session.id, createdAt: session.createdAt, expiresAt: session.expiresAt, ipAddress: session.ipAddress || "Private", userAgent: session.userAgent || "Unknown device", isCurrent: session.tokenHash === currentHash })); }), revokeSession: publicProcedure.input(withCsrf({ sessionId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireCsrf(ctx, input.csrfToken); const user = await currentLocalUser(ctx); if (!user) throw new TRPCError({ code: "UNAUTHORIZED" }); await revokeAuthSession(user.id, input.sessionId); return { success: true }; }), revokeOtherSessions: publicProcedure.input(withCsrf({})).mutation(async ({ ctx, input }) => { requireCsrf(ctx, input.csrfToken); const user = await currentLocalUser(ctx); const currentToken = readCookie(ctx.req, LOCAL_SESSION_COOKIE); if (!user || !currentToken) throw new TRPCError({ code: "UNAUTHORIZED" }); await revokeOtherAuthSessions(user.id, currentToken); return { success: true }; }) }),
  twoFactor: router({
    status: publicProcedure.query(async ({ ctx }) => { const user = await currentLocalUser(ctx); return { authenticated: Boolean(user), enabled: user ? Boolean(user.twoFactorEnabled) : false, ready: true, guidance: "Use an authenticator app and store recovery codes offline." }; }),
    beginEnrollment: publicProcedure.input(withCsrf({})).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const user = await currentLocalUser(ctx); if (!user) throw new TRPCError({ code: "UNAUTHORIZED", message: "Please sign in." }); const secret = generateSecret(); const enrollmentId = randomBytes(16).toString("hex"); await updateTwoFactorEnrollment(user.id, { twoFactorSecret: secret, twoFactorEnrollmentId: enrollmentId, twoFactorEnabled: 0 }); return { ready: true, enrollmentId, secret, otpauthUri: generateURI({ issuer: "Haven", label: user.email || "account", secret }), guidance: "Add this secret to your authenticator, then submit the six-digit code. Save recovery codes offline." }; }),
    verifyEnrollment: publicProcedure.input(withCsrf({ enrollmentId: z.string().length(32), code: z.string().regex(/^\d{6}$/) })).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const user = await currentLocalUser(ctx); if (!user || user.twoFactorEnrollmentId !== input.enrollmentId || !user.twoFactorSecret || !(await verify({ secret: user.twoFactorSecret, token: input.code })).valid) throw new TRPCError({ code: "BAD_REQUEST", message: "That verification code is invalid or expired." }); const recoveryCodes = Array.from({ length: 8 }, () => randomBytes(5).toString("hex")); const hashedCodes = await Promise.all(recoveryCodes.map(code => bcrypt.hash(code, 12))); await updateTwoFactorEnrollment(user.id, { twoFactorEnabled: 1, twoFactorEnrollmentId: null, recoveryCodesHash: JSON.stringify(hashedCodes) }); return { ready: true, accepted: true, recoveryCodes, guidance: "Download or print these recovery codes now. They will not be shown again." }; }),
    verifyLogin: publicProcedure.input(withCsrf({ code: z.string().regex(/^\d{6}$/) })).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const token = readCookie(ctx.req, LOCAL_SESSION_COOKIE); const user = await currentLocalUser(ctx); if (!token || !user?.twoFactorEnabled || user.sessionTwoFactorVerified || !user.twoFactorSecret || !(await verify({ secret: user.twoFactorSecret, token: input.code })).valid) throw new TRPCError({ code: "UNAUTHORIZED", message: "The authenticator code is invalid." }); await verifyAuthSessionTwoFactor(token); void addSecurityEvent(user.id, "login.2fa_verified", requestMetadata(ctx)); return { success: true, user: safeUser({ ...user, sessionTwoFactorVerified: 1 }) }; }),
    redeemRecoveryCode: publicProcedure.input(withCsrf({ code: z.string().trim().min(8).max(32) })).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const token = readCookie(ctx.req, LOCAL_SESSION_COOKIE); const user = await currentLocalUser(ctx); if (!token || !user?.twoFactorEnabled || user.sessionTwoFactorVerified) throw new TRPCError({ code: "UNAUTHORIZED", message: "Complete the authenticator step first." }); const hashes: string[] = user.recoveryCodesHash ? JSON.parse(user.recoveryCodesHash) : []; const index = await (async () => { for (let i = 0; i < hashes.length; i++) if (await bcrypt.compare(input.code, hashes[i] || "")) return i; return -1; })(); if (index < 0) throw new TRPCError({ code: "UNAUTHORIZED", message: "That recovery code is invalid or already used." }); hashes.splice(index, 1); await updateTwoFactorEnrollment(user.id, { recoveryCodesHash: JSON.stringify(hashes) }); await verifyAuthSessionTwoFactor(token); void addSecurityEvent(user.id, "login.recovery_code_used", requestMetadata(ctx)); return { success: true, remainingCodes: hashes.length }; }),
  }),
  recovery: router({
    verifyEmail: publicProcedure.input(z.object({ token: z.string().min(32).max(128) })).mutation(async ({ input }) => { const user = await consumeEmailVerificationToken(hashSessionToken(input.token)); if (!user) throw new TRPCError({ code: "BAD_REQUEST", message: "That verification link is invalid or expired." }); return { success: true }; }),
    requestPasswordReset: publicProcedure.input(withCsrf({ email: emailSchema })).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const user = await getLocalUserByEmail(input.email); if (user) { const token = randomBytes(32).toString("hex"); const expiresAt = new Date(Date.now() + TOKEN_TTL_MS); await setPasswordResetToken(user.id, hashSessionToken(token), expiresAt); try { await deliverAccountEmail({ to: input.email, kind: "reset-password", token, expiresAt }); } catch { /* Keep reset requests non-enumerating. */ } } return { accepted: true, message: "If an account matches, a reset link will be sent shortly." }; }),
    resetPassword: publicProcedure.input(withCsrf({ token: z.string().min(32).max(128), password: passwordSchema })).mutation(async ({ input, ctx }) => { requireCsrf(ctx, input.csrfToken); const user = await getUserByPasswordResetToken(hashSessionToken(input.token)); if (!user) throw new TRPCError({ code: "BAD_REQUEST", message: "That reset link is invalid or expired." }); await completePasswordReset(user.id, await bcrypt.hash(input.password, 12)); void addSecurityEvent(user.id, "account.password_reset", requestMetadata(ctx)); return { success: true }; }),
  }),
});
export type AppRouter = typeof appRouter;
